### ISSUE TITLE
New hackage revision

### ISSUE THREAD

**Issue by DrewFenwick** [awakesecurity/proto3-wire#107]
Since #106 bumped some outdated bounds, a new metadata revision to get this on hackage would unblock work to update the aeson version used by [proto3-suite](https://github.com/awakesecurity/proto3-suite).

**Comment by riz0id** [comment]
I'll have it out by the end of the week.

**Comment by riz0id** [comment]
https://hackage.haskell.org/package/proto3-wire-1.4.3
