### ISSUE TITLE
Make a release to Hackage

### ISSUE THREAD

**Issue by ndmitchell** [awakesecurity/proto3-wire#53]
At Digital Asset we are using proto3-wire and proto3-suite. We are just in the process of switching to the upstream versions. However, we're pulling them straight from your git repo, and while we trust you, there's nothing to stop you from deleting the git repo. Any chance of a release to Hackage (ideally Stackage) then we could use all our standard code-mirroring stuff to ensure we were resilient in the face of removals?

If you'd rather not, we'll fork the projects into our org as a backup, but continue to use yours as the source.

**Comment by ixmatus** [comment]
We don't have a problem releasing to Hackage, I think a combination of not being ready and other priorities taking up time has caused us to not do that but since there's someone who wants it released it's perhaps time to do so :) I'll repeat the question internally just in case.

**Comment by ndmitchell** [comment]
Thanks! To be clear, proto3-wire and proto3-suite would be useful, although if you're willing, I suggest holding off a few days until I've got our switch upstream landed.

grpc-haskell and grpc-haskell-core we still have wildly forked versions, so once we are upstream on proto3-* we hope to do the grpc-haskell-* ones next. Releasing them at this point wouldn't be useful (although feel free if you want to).

**Comment by gbaz** [comment]
can we close this?

https://hackage.haskell.org/package/proto3-wire
https://hackage.haskell.org/package/proto3-suite

i think the grpc- stuff is only half done still though...

**Comment by ndmitchell** [comment]
Any chance of also adding them to Stackage?

For the grpc- stuff we're still on forked versions with many changes. Once I rationalise our environment to using upstream then I'll be asking for a release :)

**Comment by Gabriel439** [comment]
Maybe.  Let's just do Hackage for now

**Comment by riz0id** [comment]
https://hackage.haskell.org/package/proto3-wire-1.4.3
